# Generated by Django 4.2.16 on 2024-10-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_recipe_ingridients_remove_recipe_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingridients',
            new_name='ingredients',
        ),
    ]
