# Generated by Django 4.2.16 on 2024-10-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_rename_ingridient_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingridient',
            name='ingridient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipe.ingredient'),
        ),
    ]
