# Generated by Django 4.2.16 on 2024-10-03 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeuser',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipe.recipe'),
        ),
    ]
