# Generated by Django 4.2.16 on 2024-10-03 01:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0008_alter_recipeuser_recipe_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeuser',
            unique_together={('user_id', 'recipe_id')},
        ),
    ]
