# Generated by Django 4.2.16 on 2024-10-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_recipeuser_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipeingridient', through='recipe.RecipeIngridient', to='recipe.ingredient', verbose_name='Ингридиенты'),
        ),
    ]
