# Generated by Django 4.2.16 on 2024-10-04 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingridient',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ing', to='recipe.recipe'),
        ),
    ]
