# Generated by Django 4.2.16 on 2024-10-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_alter_shoppinglist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeuser',
            unique_together=set(),
        ),
    ]
