# Generated by Django 4.2.16 on 2024-10-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_alter_recipeuser_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
    ]
