# Generated by Django 4.2.16 on 2024-10-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_recipe_is_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
    ]
