# Generated by Django 4.2.16 on 2024-10-12 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0018_remove_recipe_is_favorited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipe.RecipeIngridient', to='recipe.ingredient', verbose_name='Ингридиенты'),
        ),
        migrations.AlterField(
            model_name='recipeingridient',
            name='ingridient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipe.ingredient'),
        ),
    ]
