# Generated by Django 4.2.16 on 2024-10-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0020_recipe_is_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
