# Generated by Django 4.2.16 on 2024-09-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avantar',
            new_name='avatar',
        ),
    ]
