# Generated by Django 4.2.16 on 2024-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_avantar_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(upload_to='', verbose_name='Ссылка на аватар'),
        ),
    ]
